[package]
name = "PalmShellRust"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
colored = "3.0.0"
colorgrad = { version = "0.8.0", features = ["preset"] }
os_pipe = "1.2.3"
rand = "0.9.2"
rustyline = "17.0.2"
whoami = "1.6.1"
