[package]
name = "PalmShellRust"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
colored = "3.0.0"
libc = "0.2.177"
nix = { version = "0.30.1", features = ["process", "signal"] }
rustyline = "17.0.2"
whoami = "1.6.1"
